### ISSUE TITLE
Subject Heading and Term Source Codes

### ISSUE THREAD

**Issue by kiegel** [lcnetdev/marc2bibframe#211]
A suggestion that the list Subject Heading and Term Source Codes (http://www.loc.gov/standards/sourcelist/subject.html) be converted to a thesaurus.  This would better support linked data, and URIs instead of literals could be used to indicated sources.

Instead of using bf:authoritySource, a parallel property with a different range, such as bf:authoritySourceUri, could be created.  Alternately, madsrdf:isMemberOfMADSScheme could be used.

**Comment by ntra00** [comment]
done. please review at id.loc.gov/vocabulary/subjectSchemes.
And it's in use here (added in transformation on lastest commit)
bibframe.org/resources/hCy1421257824/
Note the new n3 notation option.
