### ISSUE TITLE
var $edition-instances is never used

### ISSUE THREAD

**Issue by ndushay** [lcnetdev/marc2bibframe#249]
I have been trying to reverse engineer some of the algorithms in use here, e.g. "when is an bf:Instance in the output."

In the course of this, I discovered a number of things, such as:

1.  the $edition-instances variable here:
https://github.com/lcnetdev/marc2bibframe/blob/master/modules/module.MBIB-2-BIBFRAME-Shared.xqy#L560
is never used.
This also means that generate-instance-from250 isn't necessary.

2.  there are comments pertaining to parameters that aren't there, e.g.

https://github.com/lcnetdev/marc2bibframe/blob/master/modules/module.MBIB-2-BIBFRAME-Shared.xqy#L1193

etc.

No one is perfect -- the question is ... should I be submitting pull requests for this sort of thing?

**Comment by kirkhess** [comment]
Yes, submit a pull request and we'll review it, thanks!

**Comment by ntra00** [comment]
removed $edition-instances from processing
