### ISSUE TITLE
MARC holdings data (bf:heldBy)

### ISSUE THREAD

**Issue by Timathom** [lcnetdev/marc2bibframe#252]
I have a MARC record for a serial, with an associated holdings record: http://bibframe.org/resources/Zjm1442425858/marcxml.xml.

The converter is incorrectly using data from the first 866 field as the value of `bf:heldBy`: http://bibframe.org/resources/Zjm1442425858/bibframe.n3. 

Not sure why this is happening, since I don't see anyplace in the code where the 866 is being used.

**Comment by ntra00** [comment]
fixed
